// src/domains/caregiverManagement/api/graphql/resolvers/CaregiverResolver.ts
import { Resolver, Query, Mutation, Arg, Ctx } from "type-graphql";
import { StaffType } from "../types/StaffTypes";
import { RegisterCaregiverInputGql, UpdateCaregiverContactInputGql, AddCaregiverCertificationInputGql } from "../inputs/CreateCaregiverInput";
import { StaffMap } from "../../infrastructure/mappers/StaffMaps";
import { CreateStaffProfileUseCase } from "../../application/useCases/CreateCaregiverProfileUseCas";
import { UpdateCaregiverContactUseCase } from "../../application/useCases/UpdateCaregiverContactUseCase";
import { GraphQLContext } from '../../../../lib/graphqlContext';
import { StaffRole } from "../../domain/entities/Staff";

@Resolver(() => StaffType)
export class StaffResolvers {

    @Query(() => [StaffType])
    async caregiverList(
        @Ctx() ctx: GraphQLContext,
        @Arg("search", () => String, { nullable: true }) search: string
    ): Promise<StaffType[]> {
        const { repo } = ctx.caregiverManagement;
        const caregivers = await repo.list({ search });

        return caregivers.map((caregiver: any) => StaffMap.toDTO(caregiver));
    }

    @Query(() => StaffType, { nullable: true })
    async caregiverById(
        @Arg("id", () => String) id: string,
        @Ctx() ctx: GraphQLContext
    ): Promise<StaffType | null> {
        const caregiver = await ctx.caregiverManagement.repo.getById(id);
        return caregiver ? StaffMap.toDTO(caregiver) : null;
    }

    @Mutation(() => StaffType)
    async registerCaregiver(
        @Arg("input", () => RegisterCaregiverInputGql) input: RegisterCaregiverInputGql,
        @Ctx() ctx: GraphQLContext
    ): Promise<StaffType> {
        const useCase = new CreateStaffProfileUseCase(ctx.caregiverManagement.repo);

        // CRITICAL: Notice passwordHash is completely gone from this use case payload
        const caregiver = await useCase.execute({
            id: input.id, // This matches the ID generated by IdentityAccess!
            firstName: input.firstName,
            lastName: input.lastName,
            email: input.email,
            phone: input.phone ?? null,
            role: input.role as unknown as StaffRole,
            employmentType: input.employmentType,
            hireDate: input.hireDate,
            birthDate: input.birthDate,
        });

        return StaffMap.toDTO(caregiver);
    }

    @Mutation(() => StaffType)
    async updateCaregiverContact(
        @Arg("input", () => UpdateCaregiverContactInputGql) input: UpdateCaregiverContactInputGql,
        @Ctx() ctx: GraphQLContext
    ): Promise<StaffType> {
        const useCase = new UpdateCaregiverContactUseCase(ctx.caregiverManagement.repo);
        const staff = await useCase.execute({
            id: input.id,
            phone: input.phone,
        });
        return StaffMap.toDTO(staff);
    }

}