services:
  api:
    build:
      context: ./apps/api

    ports:
      - "4000:4000"

    volumes:
      - type: bind
        source: ./apps/api/
        target: /app/api/

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./apps/api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

  staff-portal:
    build:
      context: ./apps/staff-portal
    
    ports:
      - "5173:5173"

    volumes:
      - type: bind
        source: ./apps/staff-portal
        target: /app/staff-portal

    environment:
      - API_URL=http://localhost:4000/graphql

    depends_on:
      - postgres
      - api

volumes:
  pgdata:

          