services:
  snaptuki-api:
    build:
      context: ./apps/api

    ports:
      - "4000:4000"

    volumes:
      - type: bind
        source: ./apps/api/
        target: /app/api/

    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./apps/api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

          