// src/domains/taskManagement/infrastructure/repos/PrismaTaskRepo.ts

import { ITaskRepo } from "../../application/interfaces/ITaskRepo";
import { Task, TaskStatus } from "../../domain/entities/Task";
import { TaskMap } from "../mappers/TaskMap";
import { PrismaClient } from "../../../../generated/prisma";

export class PrismaTaskRepo implements ITaskRepo {
  constructor(private readonly prisma: PrismaClient) { }

  // Centralize the includes so we never miss a nested relation and crash the mapper
  private readonly aggregateIncludes = {
    checklist: true,
  };

  async getById(id: string): Promise<Task | null> {
    const row = await this.prisma.task.findUnique({
      where: { id },
      include: this.aggregateIncludes,
    });
    return row ? TaskMap.toDomain(row as any) : null;
  }

  async list(params?: {
    take?: number; skip?: number; search?: string | null;
    status?: string | null; caregiverId?: string | null; residentId?: string | null;
    startDate?: Date | null; endDate?: Date | null;
  }) {
    const {
      take = 50, skip = 0, search, status, caregiverId, residentId, startDate, endDate
    } = params ?? {};

    const rows = await this.prisma.task.findMany({
      where: {
        AND: [
          residentId ? { residentId } : {},
          caregiverId ? { assignedStaffId: caregiverId } : {},
          status ? { status: status as any } : {},
          startDate || endDate ? {
            dueAt: {
              ...(startDate && { gte: startDate }),
              ...(endDate && { lte: endDate }),
            }
          } : {},
          search ? {
            OR: [
              { title: { contains: search, mode: 'insensitive' } },
              { description: { contains: search, mode: 'insensitive' } },
            ]
          } : {},
        ]
      },
      take,
      skip,
      orderBy: [{ dueAt: "asc" }, { createdAt: "desc" }],
      include: {
        checklist: true, assignedStaff: true
      },
    });

    return rows;
  }

  /**
   * --- THE DDD UPSERT PATTERN ---
   * Replaces both create() and save().
   */
  async save(task: Task): Promise<void> {
    const data = TaskMap.toPersistence(task);
    const state = task.snapshot(); // Extract snapshot strictly to get immutable properties like ID and createdBy

    await this.prisma.task.upsert({
      where: { id: state.id },

      // CREATE: Strip out `deleteMany` for the initial insert
      create: {
        id: state.id,
        title: data.title,
        description: data.description,
        category: data.category as any,
        priority: data.priority as any,
        status: data.status as any,
        dueAt: new Date(data.dueAt),
        startedAt: data.startedAt,
        completedAt: data.completedAt,
        residentId: data.residentId,
        assignedStaffId: data.assignedCaregiverId,
        completionNotes: data.completionNotes ?? [],

        checklist: {
          create: data.checklist.create // Map directly from the persistence payload
        }
      },

      // UPDATE: Pass the full Wipe-and-Replace payload generated by the mapper
      update: {
        id: data.id,
        title: data.title,
        description: data.description,
        category: data.category as any,
        priority: data.priority as any,
        status: data.status,
        dueAt: data.dueAt,
        startedAt: data.startedAt,
        completedAt: data.completedAt,
        completionNotes: data.completionNotes ? data.completionNotes : [''],

        // 1. FIX: Use nested connect for the resident relation
        resident: {
          connect: { residentId: state.residentId }
        },

        // ... your existing checklist mapping ...
    checklist: {
      deleteMany: {},
      create: state.checklist.map(item => ({
        id: item.id,
        label: item.label,
        isRequired: item.isRequired,
        isCompleted: item.isCompleted,
        completedAt: item.completedAt
      }))
    }
      },
    });
  }

  async delete(id: string): Promise<void> {
    await this.prisma.task.delete({ where: { id } });
  }

  // --- Background Worker Queries ---

  async findImpendingTasks(targetTime: Date, currentTime: Date): Promise<Task[]> {
    const rows = await this.prisma.task.findMany({
      where: {
        // Look for tasks that are not done yet
        status: { in: ['PENDING'] },
        dueAt: {
          lte: targetTime,
          gt: currentTime,
        }
      },
      include: this.aggregateIncludes,
    });

    return rows.map(row => TaskMap.toDomain(row as any)).filter((t): t is Task => t !== null);
  }

  async findMissedTasks(currentTime: Date): Promise<Task[]> {
    const rows = await this.prisma.task.findMany({
      where: {
        // Include ASSIGNED tasks; a caregiver being assigned doesn't mean it's not missed if it's late!
        status: { in: ['PENDING'] },
        dueAt: { lt: currentTime }
      },
      include: this.aggregateIncludes,
    });

    return rows.map(row => TaskMap.toDomain(row as any)).filter((t): t is Task => t !== null);
  }
}