// src/domains/residentManagement/infrastructure/repos/PrismaResidentRepo.ts

import { IResidentRepo } from "../../../../residentManagement/application/interfaces/IResidentRepo";
import { Resident } from "../../../../residentManagement/domain/entities/Resident";
import { ResidentMap } from "../mappers/ResidentMap";
import { PrismaClient } from "../../../../../generated/prisma";

export class PrismaResidentRepo implements IResidentRepo {

  constructor(private readonly prisma: PrismaClient) { }

  // --- 1. Centralized Includes ---
  // Define this once to guarantee you never miss a relation and cause data loss
  private readonly aggregateIncludes = {
    allergies: true,
    medications: true,
    emergencyContacts: true,
    taskAssignments: true, 
    tasks: true, // Optional: Only include if you intend to load full care history every time
  };

  async getById(id: string) {
    return await this.prisma.resident.findUnique({
      where: { residentId: id },
      include: this.aggregateIncludes,
    });
  }

  async getByMRN(mrn: string) {
    const row = await this.prisma.resident.findUnique({
      where: { mrn },
      include: this.aggregateIncludes,
    });
    return row;
  }

  async list(params?: { take?: number; skip?: number; search?: string | null; mobilityLevel?: string | null; }) {
    const { take = 50, skip = 0, search, mobilityLevel } = params ?? {};
    
    const rows = await this.prisma.resident.findMany({
      where: {
        AND: [
          mobilityLevel ? { mobilityLevel: mobilityLevel as any } : {},
          search
            ? {
                OR: [
                  { firstName: { contains: search, mode: "insensitive" } },
                  { lastName: { contains: search, mode: "insensitive" } },
                  { mrn: { contains: search, mode: "insensitive" } },
                ],
              }
            : {},
        ],
      },
      take,
      skip,
      orderBy: { createdAt: "desc" },
      include: this.aggregateIncludes,
    });

    // Map safely, filtering out any potential nulls
    return rows;
  }

  /**
   * --- THE DDD UPSERT PATTERN ---
   * Replaces both create() and update/save().
   */
  async save(resident: Resident): Promise<void> {
    const data = ResidentMap.toPersistence(resident);
    const state = resident.snapshot(); // Get the ID safely without breaking encapsulation

    await this.prisma.resident.upsert({
      where: { residentId: state.residentId },
      
      // CREATE: We must strip the `deleteMany` commands out for the initial insert
      create: {
        residentId: state.residentId,
        agencyId: data.agencyId,
        mrn: data.mrn,
        firstName: data.firstName,
        lastName: data.lastName,
        ssn: data.ssn,
        birthDate: data.birthDate,
        gender: data.gender,
        status: data.status,
        mobilityLevel: data.mobilityLevel,
        room: data.room,
        // Map the creations directly without deleteMany
        allergies: { create: state.allergies },
        medications: { create: state.medications },
        emergencyContacts: { create: state.emergencyContacts },
        taskAssignments: { create: state.taskAssignments },
      },

      // UPDATE: Pass the full Wipe-and-Replace payload generated by the mapper
      update: data,
    });
  }

  async delete(id: string): Promise<void> {
    await this.prisma.resident.delete({ 
      where: { residentId: id } 
    });
  }
}