// src/domains/taskManagement/domain/entities/ChecklistItem.ts

// 1. Explicit Read-Only State for the Mapper and Snapshot
export interface ChecklistItemState {
  id: string;
  label: string;
 
}

// 2. Internal Encapsulated Props
interface ChecklistItemProps {
  id: string;
  label: string;
}

export interface UpdateChecklistItemProps {
  label?: string;
}

export class ChecklistItem {
  private props: ChecklistItemProps;

  private constructor(props: ChecklistItemProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For adding a BRAND NEW item to a task ---
   */
  public static createNew(props: {
    id: string; // Generated by Orchestrator/Use Case
    label: string;
  }): ChecklistItem {
    if (!props.id || !props.label.trim()) {
      throw new Error("ChecklistItem requires an ID and a label.");
    }

    return new ChecklistItem({
      id: props.id,
      label: props.label.trim(),
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  public static restore(snapshot: ChecklistItemState): ChecklistItem {
    return new ChecklistItem({ ...snapshot });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): ChecklistItemState {
    return {
      id: this.props.id,
      label: this.props.label,
    };
  }

  /**
   * --- SELECTIVE GETTERS & INQUIRIES (For Aggregate Root Rules) ---
   */
  get id(): string {
    return this.props.id;
  }


  /**
   * --- DOMAIN BEHAVIORS ---
   */
  
  public update(props: UpdateChecklistItemProps): void {
    if (props.label !== undefined) {
      if (!props.label.trim()) throw new Error("Label cannot be empty.");
      this.props.label = props.label.trim();
    }
    
  }

  /**
   * Safely toggles the completion status and records the audit trail.
   */
  public toggle(done: boolean, byCaregiverId: string | null): void {
    if (done && !byCaregiverId) {
      throw new Error("A Caregiver ID is required to mark an item as completed.");
    }

  }
}