// src/domains/taskManagement/domain/entities/ChecklistItem.ts

// 1. Explicit Read-Only State for the Mapper and Snapshot
export interface ChecklistItemState {
  id: string;
  label: string;
  isRequired: boolean;
  isCompleted: boolean;
  completedAt: Date | null;
  completedByCaregiverId: string | null;
}

// 2. Internal Encapsulated Props
interface ChecklistItemProps {
  id: string;
  label: string;
  isRequired: boolean;
  isCompleted: boolean;
  completedAt: Date | null;
  completedByCaregiverId: string | null;
}

export interface UpdateChecklistItemProps {
  label?: string;
  isRequired?: boolean;
}

export class ChecklistItem {
  private props: ChecklistItemProps;

  private constructor(props: ChecklistItemProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For adding a BRAND NEW item to a task ---
   */
  public static createNew(props: {
    id: string; // Generated by Orchestrator/Use Case
    label: string;
    isRequired?: boolean;
  }): ChecklistItem {
    if (!props.id || !props.label.trim()) {
      throw new Error("ChecklistItem requires an ID and a label.");
    }

    return new ChecklistItem({
      id: props.id,
      label: props.label.trim(),
      isRequired: props.isRequired ?? false,
      isCompleted: false,
      completedAt: null,
      completedByCaregiverId: null,
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  public static restore(snapshot: ChecklistItemState): ChecklistItem {
    return new ChecklistItem({ ...snapshot });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): ChecklistItemState {
    return {
      id: this.props.id,
      label: this.props.label,
      isRequired: this.props.isRequired,
      isCompleted: this.props.isCompleted,
      completedAt: this.props.completedAt,
      completedByCaregiverId: this.props.completedByCaregiverId,
    };
  }

  /**
   * --- SELECTIVE GETTERS & INQUIRIES (For Aggregate Root Rules) ---
   * These are exposed strictly so the `Task` aggregate can validate 
   * completion rules (e.g., `item.isRequired() && !item.isCompleted()`).
   */
  get id(): string {
    return this.props.id;
  }

  public isRequired(): boolean {
    return this.props.isRequired;
  }

  public isCompleted(): boolean {
    return this.props.isCompleted;
  }

  /**
   * --- DOMAIN BEHAVIORS ---
   */
  
  public update(props: UpdateChecklistItemProps): void {
    if (props.label !== undefined) {
      if (!props.label.trim()) throw new Error("Label cannot be empty.");
      this.props.label = props.label.trim();
    }
    if (props.isRequired !== undefined) {
      this.props.isRequired = props.isRequired;
    }
  }

  public toggle(done: boolean, byCaregiverId: string | null): void {
    this.props.isCompleted = done;
    this.props.completedAt = done ? new Date() : null;
    this.props.completedByCaregiverId = done ? byCaregiverId : null;
  }
}