// src/domains/taskManagement/domain/entities/Task.ts
import { Title } from "../valueObjects/Title";
import { Description } from "../valueObjects/Description";
import { ChecklistItem } from "./ChecklistItem";

// 1. DOMAIN ENUMS (Severing the Prisma dependency)
export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  MISSED = "MISSED" // Essential for your automated Task Center MVP requirements!
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum TaskCategory {
  CARE = "CARE",
  MEDICATION = "MEDICATION",
  HYGIENE = "HYGIENE",
  VITALS = "VITALS",
  OTHER = "OTHER"
}

// 2. EXPLICIT READ-ONLY STATE (For Mappers and DTOs)
export interface TaskState {
  id: string;
  title: string; // Unwrapped Value Object
  description: string | null; // Unwrapped Value Object
  category: TaskCategory;
  priority: TaskPriority;
  status: TaskStatus;
  residentId: string;
  assignedCaregiverId: string;
  dueAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  completedByCaregiverId: string | null;
  completionNotes: string[] | null;
  checklist: any[]; // Assuming ChecklistItem has its own snapshot() returning state
  createdByUserId: string;
  createdAt: Date;
  updatedAt: Date;
}

// 3. INTERNAL ENCAPSULATED PROPS
export interface TaskProps {
  id: string;
  title: Title;
  description: Description | null;
  category: TaskCategory;
  priority: TaskPriority;
  status: TaskStatus;
  residentId: string;
  assignedCaregiverId: string;
  dueAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  completedByCaregiverId: string | null;
  completionNotes: string[] | null;
  checklist: ChecklistItem[];
  createdByUserId: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface UpdateTaskProps {
  title?: string;
  description?: string | null;
  priority?: TaskPriority;
  dueAt?: Date | null;
}

export class Task {
  private props: TaskProps;

  private constructor(props: TaskProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For spawning a BRAND NEW task ---
   */
  static createNew(props: {
    id: string; // Enforced! Generated by the Use Case
    title: string;
    description?: string | null;
    category?: TaskCategory;
    priority?: TaskPriority;
    residentId: string;
    dueAt: Date;
    checklist?: ChecklistItem[];
    assignedCaregiverId: string;
    createdByUserId: string;
  }): Task {
    if (!props.id || !props.title.trim() || !props.createdByUserId) {
      throw new Error("Missing critical Task properties (id, title, or creator).");
    }

    const now = new Date();

    return new Task({
      id: props.id,
      title: Title.create(props.title),
      description: props.description ? Description.create(props.description) : null,
      category: props.category ?? TaskCategory.CARE,
      priority: props.priority ?? TaskPriority.MEDIUM,
      status: TaskStatus.PENDING,
      residentId: props.residentId,
      assignedCaregiverId: props.assignedCaregiverId,
      dueAt: props.dueAt,
      startedAt: null,
      completedAt: null,
      completedByCaregiverId: null,
      completionNotes: null,
      checklist: props.checklist ?? [],
      createdByUserId: props.createdByUserId,
      createdAt: now,
      updatedAt: now,
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  static restore(snapshot: TaskState): Task {
    return new Task({
      id: snapshot.id,
      title: Title.create(snapshot.title),
      description: snapshot.description ? Description.create(snapshot.description) : null,
      category: snapshot.category,
      priority: snapshot.priority,
      status: snapshot.status,
      residentId: snapshot.residentId,
      assignedCaregiverId: snapshot.assignedCaregiverId,
      dueAt: snapshot.dueAt,
      startedAt: snapshot.startedAt,
      completedAt: snapshot.completedAt,
      completedByCaregiverId: snapshot.completedByCaregiverId,
      completionNotes: snapshot.completionNotes,
      checklist: snapshot.checklist.map((c: any) => ChecklistItem.restore(c)),
      createdByUserId: snapshot.createdByUserId,
      createdAt: snapshot.createdAt,
      updatedAt: snapshot.updatedAt,
    });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): TaskState {
    return {
      id: this.props.id,
      title: this.props.title.value, // Extract VO string
      description: this.props.description ? this.props.description.value : null,
      category: this.props.category,
      priority: this.props.priority,
      status: this.props.status,
      residentId: this.props.residentId,
      assignedCaregiverId: this.props.assignedCaregiverId,
      dueAt: this.props.dueAt,
      startedAt: this.props.startedAt,
      completedAt: this.props.completedAt,
      completedByCaregiverId: this.props.completedByCaregiverId,
      completionNotes: this.props.completionNotes,
      checklist: this.props.checklist.map(c => c.snapshot()),
      createdByUserId: this.props.createdByUserId,
      createdAt: this.props.createdAt,
      updatedAt: this.props.updatedAt,
    };
  }

  /**
   * --- SELECTIVE GETTERS (For Aggregate Root Rules) ---
   */
  get id(): string {
    return this.props.id;
  }

  // --- Domain Behaviors ---

  // Inside src/domains/taskManagement/domain/entities/Task.ts

  public update(props: UpdateTaskProps): void {
    if (props.title !== undefined) {
      if (props.title.trim() === '') throw new Error("Task title cannot be empty.");
      this.props.title = Title.create(props.title);
    } 
    // FIXED TYPO HERE (removed "}checklist")
    
    if (props.description !== undefined) {
      this.props.description = props.description ? Description.create(props.description) : null;
    }
    
    if (props.priority) this.props.priority = props.priority;

    this.thisTrackUpdate();
  }

  // ADD THIS NEW METHOD:
  public updateChecklist(newItems: { id: string, label: string}[]): void {
  
    this.props.checklist = newItems.map(item => 
      ChecklistItem.restore({
        id: item.id,
        label: item.label,
      })
    );

    this.thisTrackUpdate();
  }

  public assign(caregiverId: string): void {
    this.props.assignedCaregiverId = caregiverId;
    this.thisTrackUpdate();
  }

  public unassign(): void {
    this.thisTrackUpdate();
  }

  public start(now: Date = new Date()): void {
    if (this.props.status === TaskStatus.COMPLETED || this.props.status === TaskStatus.CANCELLED) {
      throw new Error("Cannot start a finished task.");
    }
    this.props.status = TaskStatus.IN_PROGRESS;
    this.props.startedAt = now;
    this.thisTrackUpdate();
  }

  public complete(byCaregiverId: string, notes?: string[] | null, now: Date = new Date()): void {
    if (this.props.status === TaskStatus.CANCELLED) {
      throw new Error("Cannot complete a cancelled task.");
    }
    

    this.props.status = TaskStatus.COMPLETED;
    this.props.completedAt = now;
    this.props.completedByCaregiverId = byCaregiverId;
    if (notes) this.props.completionNotes = notes;
    
    this.thisTrackUpdate();
  }

  public cancel(reason: string, now: Date = new Date()): void {
    if (!reason.trim()) throw new Error("A cancellation reason is required.");
    this.props.status = TaskStatus.CANCELLED;
    this.props.completionNotes = [reason];
    this.thisTrackUpdate();
  }

  public markAsMissed(): void {
    if (this.props.status === TaskStatus.COMPLETED || this.props.status === TaskStatus.CANCELLED) {
      return;
    }
    this.props.status = TaskStatus.MISSED;
    this.thisTrackUpdate();
  }

  public addChecklistItem(item: ChecklistItem): void {
    const exists = this.props.checklist.some(i => i.id === item.id);
    if (!exists) {
        this.props.checklist.push(item);
        this.thisTrackUpdate();
    }
  }

  public toggleChecklistItem(itemId: string, done: boolean, byCaregiverId: string | null): void {
    if (this.props.status === TaskStatus.CANCELLED) {
      throw new Error("Cannot update checklist on a cancelled task.");
    }

    const item = this.props.checklist.find((i) => i.id === itemId);
    if (!item) {
      throw new Error(`Checklist item with ID ${itemId} not found.`);
    }

    item.toggle(done, byCaregiverId);

    this.thisTrackUpdate();
  }

  private thisTrackUpdate(): void {
    this.props.updatedAt = new Date();
  }
}