// src/domains/residentManagement/domain/entities/ChecklistItem.ts

// 1. Explicit Read-Only State for the Mapper and Snapshot
export interface ChecklistItemState {
  id: string;
  label: string;
  isRequired: boolean;
  isCompleted: boolean;
  completedAt: Date | null;
}

// 2. Internal Encapsulated Props
interface ChecklistItemProps {
  id: string;
  label: string;
  isRequired: boolean;
  isCompleted: boolean;
  completedAt: Date | null;
}

export class ChecklistItem {
  private props: ChecklistItemProps;

  private constructor(props: ChecklistItemProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For spawning a new task from a template ---
   */
  public static createNew(props: {
    id: string; // Generated by Orchestrator/Use Case
    label: string;
    isRequired?: boolean;
  }): ChecklistItem {
    if (!props.id || !props.label.trim()) {
      throw new Error("Checklist item requires an ID and a label.");
    }

    return new ChecklistItem({
      id: props.id,
      label: props.label.trim(),
      isRequired: props.isRequired ?? false,
      isCompleted: false,
      completedAt: null,
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  public static restore(snapshot: ChecklistItemState): ChecklistItem {
    return new ChecklistItem({ ...snapshot });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): ChecklistItemState {
    return {
      id: this.props.id,
      label: this.props.label,
      isRequired: this.props.isRequired,
      isCompleted: this.props.isCompleted,
      completedAt: this.props.completedAt,
    };
  }

  /**
   * --- SELECTIVE GETTERS (For Aggregate Root Rules) ---
   * These are exposed strictly so the `Task` aggregate can validate 
   * completion rules (e.g., `item.isRequired && !item.isCompleted`).
   */
  get id(): string {
    return this.props.id;
  }

  get isRequired(): boolean {
    return this.props.isRequired;
  }

  get isCompleted(): boolean {
    return this.props.isCompleted;
  }

  /**
   * --- DOMAIN BEHAVIORS ---
   * Replaced `toggle()` with explicit intents for better clarity in Use Cases.
   */
  public markComplete(): void {
    if (this.props.isCompleted) return;
    this.props.isCompleted = true;
    this.props.completedAt = new Date();
  }

  public markIncomplete(): void {
    if (!this.props.isCompleted) return;
    this.props.isCompleted = false;
    this.props.completedAt = null;
  }
}