// src/domains/residentManagement/domain/entities/TaskAssignment.ts

// 1. Explicit Read-Only State for the Mapper and Snapshot
export interface TaskAssignmentState {
  id: string; // FIXED: Must be a string (CUID/UUID) generated by the Use Case
  residentId: string;
  taskTemplateId: number; // Assuming templates still use Int, which is okay for static catalogues
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date; // FIXED: Added to track mutations
}

// 2. Internal Encapsulated Props
interface TaskAssignmentProps {
  id: string;
  residentId: string;
  taskTemplateId: number;
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export class TaskAssignment {
  private props: TaskAssignmentProps;

  private constructor(props: TaskAssignmentProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For adding a BRAND NEW assignment to a resident's care plan ---
   */
  public static createNew(props: {
    id: string; // Generated by the Orchestrator/Use Case
    residentId: string;
    taskTemplateId: number;
  }): TaskAssignment {
    if (!props.id || !props.residentId || !props.taskTemplateId) {
      throw new Error("TaskAssignment requires an id, residentId, and taskTemplateId.");
    }

    const now = new Date();

    return new TaskAssignment({
      id: props.id,
      residentId: props.residentId,
      taskTemplateId: props.taskTemplateId,
      isActive: true, // Always active upon creation
      createdAt: now,
      updatedAt: now,
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  public static restore(snapshot: TaskAssignmentState): TaskAssignment {
    return new TaskAssignment({ ...snapshot });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): TaskAssignmentState {
    return {
      id: this.props.id,
      residentId: this.props.residentId,
      taskTemplateId: this.props.taskTemplateId,
      isActive: this.props.isActive,
      createdAt: this.props.createdAt,
      updatedAt: this.props.updatedAt,
    };
  }

  /**
   * --- SELECTIVE GETTERS (For Aggregate Root Rules) ---
   * Expose identity fields so the Resident aggregate can find and manage them.
   */
  get id(): string {
    return this.props.id;
  }

  get taskTemplateId(): number {
    return this.props.taskTemplateId;
  }

  // --- Domain Behaviors ---

  /**
   * Pauses the recurring task (e.g., if the resident is temporarily hospitalized).
   */
  public deactivate(): void {
    if (!this.props.isActive) return;
    this.props.isActive = false;
    this.thisTrackUpdate();
  }

  /**
   * Resumes the care plan rule.
   */
  public activate(): void {
    if (this.props.isActive) return;
    this.props.isActive = true;
    this.thisTrackUpdate();
  }

  /**
   * Check if this assignment is valid for today's task generation.
   */
  public canGenerateTask(): boolean {
    return this.props.isActive;
  }

  /**
   * Automatically ticks the updatedAt timestamp on any state mutation.
   */
  private thisTrackUpdate(): void {
    this.props.updatedAt = new Date();
  }
}