// src/domains/residentManagement/domain/entities/Task.ts

// 1. DEFINE ENUMS IN THE DOMAIN (Sever the Prisma dependency!)
export enum TaskStatus {
  PENDING = "PENDING",
  IN_PROGRESS = "IN_PROGRESS",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
  MISSED = "MISSED"
}

export enum TaskPriority {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT"
}

export enum TaskCategory {
  MEDICATION = "MEDICATION",
  HYGIENE = "HYGIENE",
  NUTRITION = "NUTRITION",
  VITALS = "VITALS",
  ACTIVITY = "ACTIVITY",
  OTHER = "OTHER"
}

import { ChecklistItem } from "./ChecklistItem"; 

// 2. Explicit Read-Only State for the Mapper and Snapshot
export interface TaskState {
  id: string;
  templateId: number | null;
  residentId: string;
  visitId: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  category: TaskCategory;
  dueAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  completionNotes: string | null;
  checklist: any[]; // Assuming ChecklistItem has a snapshot() returning its state
  createdAt: Date;
  updatedAt: Date;
}

// 3. Internal Encapsulated Props
interface TaskProps {
  id: string;
  templateId: number | null;
  residentId: string;
  visitId: string | null;
  status: TaskStatus;
  priority: TaskPriority;
  category: TaskCategory;
  dueAt: Date;
  startedAt: Date | null;
  completedAt: Date | null;
  completionNotes: string | null;
  checklist: ChecklistItem[];
  createdAt: Date;
  updatedAt: Date;
}

export class Task {
  private props: TaskProps;

  private constructor(props: TaskProps) {
    this.props = { ...props };
  }

  /**
   * --- DOMAIN FACTORY: For spawning a new task ---
   */
  public static createNew(props: {
    id: string; // Mandatory! Generated by Use Case
    templateId?: number | null;
    residentId: string;
    priority: TaskPriority;
    category: TaskCategory;
    dueAt: Date;
    checklist?: ChecklistItem[];
  }): Task {
    const now = new Date();

    return new Task({
      id: props.id,
      templateId: props.templateId ?? null,
      residentId: props.residentId,
      visitId: null,
      status: TaskStatus.PENDING,
      priority: props.priority,
      category: props.category,
      dueAt: props.dueAt,
      startedAt: null,
      completedAt: null,
      completionNotes: null,
      checklist: props.checklist ?? [],
      createdAt: now,
      updatedAt: now
    });
  }

  /**
   * --- REHYDRATION FACTORY: For loading from Prisma ---
   */
  public static restore(snapshot: TaskState): Task {
    return new Task({
      id: snapshot.id,
      templateId: snapshot.templateId,
      residentId: snapshot.residentId,
      visitId: snapshot.visitId,
      status: snapshot.status,
      priority: snapshot.priority,
      category: snapshot.category,
      dueAt: snapshot.dueAt,
      startedAt: snapshot.startedAt,
      completedAt: snapshot.completedAt,
      completionNotes: snapshot.completionNotes,
      // Assuming restore methods exist on your child entities/VOs
      checklist: snapshot.checklist.map(c => ChecklistItem.restore(c)), 
      createdAt: snapshot.createdAt,
      updatedAt: snapshot.updatedAt,
    });
  }

  /**
   * --- THE SNAPSHOT PATTERN ---
   */
  public snapshot(): TaskState {
    return {
      id: this.props.id,
      templateId: this.props.templateId,
      residentId: this.props.residentId,
      visitId: this.props.visitId,
      status: this.props.status,
      priority: this.props.priority,
      category: this.props.category,
      dueAt: this.props.dueAt,
      startedAt: this.props.startedAt,
      completedAt: this.props.completedAt,
      completionNotes: this.props.completionNotes,
      checklist: this.props.checklist.map(c => c.snapshot()),
      createdAt: this.props.createdAt,
      updatedAt: this.props.updatedAt,
    };
  }

  /**
   * --- SELECTIVE GETTERS (For Aggregate Root Rules) ---
   */
  get id(): string {
    return this.props.id;
  }

  // --- Domain Behaviors ---

  public start(visitId: string): void {
    if (this.props.status !== TaskStatus.PENDING) {
      throw new Error("Task can only be started from PENDING status.");
    }
    this.props.status = TaskStatus.IN_PROGRESS;
    this.props.visitId = visitId;
    this.props.startedAt = new Date();
    this.thisTrackUpdate();
  }

  public complete(notes?: string): void {
    const missingRequired = this.props.checklist.some(item => item.isRequired && !item.isCompleted);
    
    if (missingRequired) {
      throw new Error("Cannot complete task: required checklist items are missing.");
    }

    this.props.status = TaskStatus.COMPLETED;
    this.props.completedAt = new Date();
    this.props.completionNotes = notes ?? null;
    this.thisTrackUpdate();
  }

  public cancel(reason: string): void {
    if (!reason.trim()) {
      throw new Error("A reason must be provided when cancelling a task.");
    }
    this.props.status = TaskStatus.CANCELLED;
    this.props.completionNotes = reason.trim();
    this.thisTrackUpdate();
  }

  public markAsMissed(): void {
    if (this.props.status === TaskStatus.COMPLETED || this.props.status === TaskStatus.CANCELLED) {
      return; // Cannot miss a task that is already finished
    }
    this.props.status = TaskStatus.MISSED;
    this.thisTrackUpdate();
  }

  /**
   * Automatically ticks the updatedAt timestamp on any state mutation.
   */
  private thisTrackUpdate(): void {
    this.props.updatedAt = new Date();
  }
}