FROM node:20-alpine AS builder

WORKDIR /usr/app/staff-portal/

COPY package*.json ./
RUN npm ci

# Copy the rest of your frontend code
COPY . .

RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /usr/app/staff-portal/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]